### ISSUE TITLE
Testing this without being a Twitch Affiliate or Partner

### ISSUE THREAD

**Issue by Bracciata** [twitchdev/channel-points-node-sample#1]
I am looking to test this in order to create a hack for the Channel Points API Hackathon and I am unable to test this because of the following error
`(node:7084) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at main (/mnt/c/Users/bracc/Documents/Dev/Personal/New folder/channel-points-node-sample/index.js:164:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
It seems I am unable to load the custom rewards, however, I am not able to set them up either because I am not an affiliate or a partner.

**Comment by milg15** [comment]
Funny that this is also the issue I am running into. I see there is a way of testing event with the twitch cli maybe there is a solution using that? :c I hope there can be a solution soon for this.

**Comment by Abinash3366** [comment]
I have the same issue, for the moment I'm using a friends channel to test my extension but its a pain because his viewers are starting to notice

**Comment by lleadbet** [comment]
The Twitch CLI can assist with this for testing with EventSub, but unfortunately there's no way to test the actual endpoints without access to Channel Points.
